### ISSUE TITLE
VASP-Support-v0.2.3 do not provide live information

### ISSUE THREAD

**Issue by Liangyan-1996** [mystery-e204/vscode-vasp-support#3] opened 2024-02-23 12:51 UTC
Hi

I have installed VASP-Support (v0.2.3) in vscode. I find that for INCAR file, the syntax highlighting function of vasp-support does work but the function of providing live information not.

best
Yan

**Comment by mystery-e204** [comment] 2024-02-23 17:50
Hey, thanks for opening an issue! I haven't touched this extension in a while so there might be a good possibility that something is broken. I'll look into it when I have time.

**Comment by mystery-e204** [comment] 2024-02-23 18:48
This seems to be caused by an invalid-certificate error when trying to retrieve information from the VASP wiki. I'll see what I can do to fix it client side first.

**Comment by tuheihei** [comment] 2024-02-25 06:31
> This seems to be caused by an invalid-certificate error when trying to retrieve information from the VASP wiki. I'll see what I can do to fix it client side first.

Hi,
The same issue here. Any help would be appreciated.
Regards,

**Comment by mystery-e204** [comment] 2024-02-25 20:18
Unfortunately, this must be fixed server side. The only thing I can do from the extension is to make the HTTP requests insecure but I would like to avoid that. The good news is that this should be fixed soon. I'll update this issue as soon as it works again.

**Comment by mystery-e204** [comment] 2024-02-26 11:29
Should be fixed now. Does it work for you, @L1angyan and @tuheihei ?

**Comment by tuheihei** [comment] 2024-02-26 11:46
> Should be fixed now. Does it work for you, @L1angyan and @tuheihei ?

@mystery-e204 
It works perfectly now! Thanks

**Closed as completed** 2024-02-26 11:57 UTC
